#!/usr/bin/env python3
"""Convert an image into a C header XeLL can blit into the Xenos framebuffer.

    python tools/img2xell.py logo.png source/lv2/logo.h --name logo --max-width 320

Emits an RGB888 array plus width/height. XeLL's draw_image() walks it with
console_pset(), which handles the framebuffer's 32x32 tile swizzle for us.

Stage 2 is gzipped and the Makefile hard-fails over 245744 bytes, so this
prints the gzipped cost of the image data to keep you honest about the budget.
A flat-colour logo compresses to almost nothing; a photo will not.
"""

import argparse
import gzip
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("needs Pillow:  python -m pip install Pillow")


def emit(path, src, name, w, h, arrayname, data, extra=""):
    body = []
    for i in range(0, len(data), 16):
        body.append("\t" + " ".join("0x%02x," % b for b in data[i:i + 16]))

    with open(path, "w", newline="\n") as f:
        f.write("/* Generated by tools/img2xell.py from %s - do not edit. */\n\n"
                % src)
        f.write("#define %s_WIDTH  %d\n" % (name.upper(), w))
        f.write("#define %s_HEIGHT %d\n" % (name.upper(), h))
        f.write(extra)
        f.write("\nstatic const unsigned char %s[] = {\n" % arrayname)
        f.write("\n".join(body))
        f.write("\n};\n")

    packed = len(gzip.compress(bytes(data), 9))
    print("%dx%d  raw %d bytes  gzipped ~%d bytes -> %s"
          % (w, h, len(data), packed, path))
    if packed > 60000:
        print("WARNING: that is a big chunk of the 245744 byte stage2 budget."
              " Try --max-width or fewer colours.")


def alpha_mask(args):
    img = Image.open(args.image).convert("RGBA")

    if args.max_width and img.width > args.max_width:
        h = round(img.height * args.max_width / img.width)
        img = img.resize((args.max_width, h), Image.LANCZOS)

    w, h = img.size
    alpha = img.getchannel("A").tobytes()
    assert len(alpha) == w * h

    emit(args.header, args.image, args.name, w, h,
         "%s_alpha" % args.name, alpha)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image", help="source image (png/jpg/bmp/gif)")
    ap.add_argument("header", help="output .h path")
    ap.add_argument("--name", default="logo", help="C identifier prefix")
    ap.add_argument("--max-width", type=int, default=0,
                    help="scale down so width <= this, keeping aspect")
    ap.add_argument("--key", default="",
                    help="transparent colour as RRGGBB; those pixels are skipped")
    ap.add_argument("--alpha-mask", action="store_true",
                    help="single-colour art: emit one alpha byte per pixel "
                         "instead of RGB, and let XeLL blend it over the "
                         "console background. A third the size, keeps AA edges.")
    args = ap.parse_args()

    if args.alpha_mask:
        return alpha_mask(args)

    img = Image.open(args.image).convert("RGB")

    if args.max_width and img.width > args.max_width:
        h = round(img.height * args.max_width / img.width)
        img = img.resize((args.max_width, h), Image.LANCZOS)

    w, h = img.size
    raw = img.tobytes()
    assert len(raw) == w * h * 3

    body = []
    for i in range(0, len(raw), 12):
        body.append("\t" + " ".join("0x%02x," % b for b in raw[i:i + 12]))

    key_line = ""
    if args.key:
        key = int(args.key.lstrip("#"), 16)
        key_line = "#define %s_KEY 0x%06x  /* skip pixels of this colour */\n" % (
            args.name.upper(), key)

    with open(args.header, "w", newline="\n") as f:
        f.write("/* Generated by tools/img2xell.py from %s - do not edit. */\n\n"
                % args.image)
        f.write("#define %s_WIDTH  %d\n" % (args.name.upper(), w))
        f.write("#define %s_HEIGHT %d\n" % (args.name.upper(), h))
        f.write(key_line)
        f.write("\nstatic const unsigned char %s_rgb[] = {\n" % args.name)
        f.write("\n".join(body))
        f.write("\n};\n")

    packed = len(gzip.compress(raw, 9))
    print("%dx%d  raw %d bytes  gzipped ~%d bytes -> %s"
          % (w, h, len(raw), packed, args.header))
    if packed > 60000:
        print("WARNING: that is a big chunk of the 245744 byte stage2 budget."
              " Try --max-width or fewer colours.")


if __name__ == "__main__":
    main()
